# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/ for more details

version: 2

jobs:
  build:
    machine:
      # https://circleci.com/docs/2.0/configuration-reference/#machine
      image: circleci/classic:201710-02
      docker_layer_caching: true
    steps:
      - checkout
      - run: docker-compose build --build-arg NODE_ENV=test api
      - run: mkdir -m 777 build && docker-compose run api sh -c 'yarn lint && yarn test --forceExit && yarn build'
      - run: docker build --tag api:latest --tag api:$CIRCLE_BUILD_NUM --build-arg NODE_ENV=production .
