version: "3"
services:
    server:
        image: johnhbenetech/mathsharebackend:latest
        env_file: .env
        ports:
            - 8080:8080
        depends_on:
            - postgresql
    postgresql:
        image: postgres:9.5.12
        ports:
            - 5433:5432
        env_file: .env
        volumes:
            - db-data:/var/lib/postgresql/data
volumes:
    db-data:
    yarn:
