version: '2'
services:
    mathshare-postgresql:
        image: postgres:9.5.12
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=password
            - POSTGRES_PASSWORD=mysecretpassword
            - POSTGRES_USER=postgres
            - POSTGRES_DB=mathshare
